
name: Maven CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  REGISTRY_USERNAME: 'omar077'
  IMAGE_NAME: 'account_service'
  JAVA_VERSION: 17
  
jobs:
  build_and_test:
    runs-on: ubuntu-latest
            
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' 
        java-version: ${{ env.JAVA_VERSION }}

    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2      

    - name: Build and test project with Maven
      run: ./mvnw -B package --file pom.xml

  build-docker-image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [build_and_test]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: ${{ env.JAVA_VERSION }}
      - name: Build Container image
        run: |
          ./mvnw -DskipTests=true clean package spring-boot:build-image \
           -Dspring-boot.build-image.imageName=${{ env.REGISTRY_USERNAME }}/$IMAGE_NAME:${{ github.sha }}
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Docker image
        run: docker push ${{ env.REGISTRY_USERNAME }}/$IMAGE_NAME:${{ github.sha }}
